### ISSUE TITLE
Launchpad streaming not working

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#549]
Opening a new stream to the launchpad doesn't work. The button spins and hangs. I captured the screenshot.
<img width="1506" alt="Screen Shot 2022-03-03 at 9 29 06 AM" src="https://user-images.githubusercontent.com/5077880/156585022-abd33ad2-d2a3-4037-8638-4e675b861837.png">

**Comment by zhyd1997** [comment]
@mikeghen 
Assign to me, I will take a look.

**Comment by zhyd1997** [comment]
( If no anyone working on this

**Comment by mikeghen** [comment]
@zhyd1997 you got it, this is top priority ⛵

**Comment by zhyd1997** [comment]
The error is occurred because someone add hooks outside of components, after removing it, I catch the real error here:
<img width="1239" alt="error screenshot" src="https://user-images.githubusercontent.com/31362988/156691008-56bc7805-6783-4486-a39a-8bb0c7cf3cd0.png">

I will figure out how to fix it.

**Comment by zhyd1997** [comment]
USDCx/RIC is missing here:
https://github.com/Ricochet-Exchange/ricochet-frontend/blob/91ee8554718030ef95ed5e3f295e763815af384c/src/constants/flowConfig.ts#L21-L55
