### ISSUE TITLE
Stats don't load without Metamask Connection

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-frontend#599]
**Describe the bug**

Data doesn't load when metamask is not connected.

**To Reproduce**

This is in staging, you can reproduce it there using a browser without metamask (e.g. Google Chrome Incognito)

**Expected behavior**

All the statistics for the markets should appear so visitors can still see the markets volume even without having metamask

**Screenshots**

<img width="2217" alt="Screen Shot 2022-03-22 at 10 29 27 AM" src="https://user-images.githubusercontent.com/5077880/159505381-68fabb71-44bb-4f8e-9f24-8da17b688281.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Google Chrome

**Additional context**

I think this has something to do with either RPC or Graph API calls. When the page loads up and I look at what network calls its making, I see its just continuously querying RPC and Graph API (see screenshot). I tried to change these RPC and Grpah APIs on my localhost but it didn't immediately fix the error. Something else must be going on.

This works ok now on app.ricochet.exchange and was previously working on staging.ricochet.exchange, which has the latest v2 app code deployed to it.

**Comment by zhyd1997** [comment]
When I added one line of code here:

<img width="1263" alt="console.error(e)" src="https://user-images.githubusercontent.com/31362988/159563664-b850b718-5026-404f-8051-c2453cafab26.png">

the error appears:

<img width="1263" alt="error" src="https://user-images.githubusercontent.com/31362988/159563725-afdbc2c2-42ff-4202-95c9-3da80fed014d.png">

that's why the page always loading without connecting the wallet.
